blank_issues_enabled: true
contact_links:
  - name: Home Assistant community
    url: https://community.home-assistant.io/
    about: For general Home Assistant questions that are not specific to Velair.
